USE billing;

ALTER TABLE gw_ids_xref ADD COLUMN last_max_id int(11) NOT NULL DEFAULT '0', 
ADD COLUMN dbUser VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN dbPass VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN dbHost VARCHAR(255) NOT NULL DEFAULT '';
